(function(){'use strict';
const base='https://dev.epicgames.com/documentation/en-us/unreal-engine/';
const sources=[['Unreal Engine 5.8 — Release Notes','https://dev.epicgames.com/documentation/unreal-engine/unreal-engine-5-8-release-notes'],['Add Movement Input',base+'BlueprintAPI/Pawn/Input/AddMovementInput'],['Enhanced Input',base+'enhanced-input-in-unreal-engine'],['Jump',base+'BlueprintAPI/Character/Jump'],['Play Anim Montage',base+'BlueprintAPI/Animation/PlayAnimMontage'],['Animation Blueprints',base+'animation-blueprints-in-unreal-engine'],['Animation Slots',base+'animation-slots-in-unreal-engine'],['Animation Blueprint Blend Nodes',base+'animation-blueprint-blend-nodes-in-unreal-engine'],['Characters',base+'characters-in-unreal-engine'],['Blueprint debugging',base+'blueprint-debugging-in-unreal-engine']];
const concepts={
 character:{title:'Character — ο παίκτης σου ως σύστημα',body:'Το ανθρωπάκι που βλέπεις δεν είναι όλος ο Character. Σκέψου τρία μέρη: το Mesh που βλέπεις, την Capsule που χρησιμοποιείται για συγκρούσεις, και το Character Movement που μετακινεί το σώμα. Ο Character είναι ειδικός Pawn με αυτά τα βασικά στοιχεία. Δεν έχει ένα ξεχωριστό Blueprint μέσα σε κάθε πόδι.',diagram:['Character','Capsule · όριο σύγκρουσης','Mesh · ό,τι βλέπεις','Movement · μετακίνηση'],tip:'Πάτησε «Κάψουλα» επάνω στη σκηνή. Το περίγραμμα είναι οπτική επεξήγηση, όχι πλήρης εξομοίωση σύγκρουσης.'},
 actor:{title:'Actor — κάτι τοποθετημένο στον κόσμο',body:'Η πόρτα είναι Actor. Ο χαρακτήρας είναι επίσης Actor, αλλά πιο εξειδικευμένος. Actor μπορεί να είναι κάτι που υπάρχει μέσα σε μια σκηνή· δεν σημαίνει απαραίτητα άνθρωπος ή εχθρός.',diagram:['Actor','Pawn · μπορεί να ελέγχεται','Character · Pawn με κίνηση'],tip:'Το Target επιλέγει ποιο αντικείμενο θα επηρεάσεις.'},
 pawn:{title:'Pawn — κάτι που μπορεί να ελεγχθεί',body:'Ένας Pawn μπορεί να ελέγχεται από παίκτη ή τεχνητή νοημοσύνη. Ένας απλός Pawn δεν περπατά μόνο επειδή του έδωσες Add Movement Input. Στο δικό μας παράδειγμα χρησιμοποιούμε Character, που περιλαμβάνει σύστημα κατανάλωσης της εισόδου κίνησης.',diagram:['Είσοδος παίκτη','Pawn','Character Movement'],tip:'Μην αλλάζεις το Target σε τυχαίο Actor επειδή είναι ορατός.'},
 mesh:{title:'Mesh — το ορατό σχήμα',body:'Τα ρούχα, τα χέρια, τα πόδια και το πρόσωπο που βλέπεις είναι γεωμετρία. Στον Unreal, ένας κινούμενος χαρακτήρας συνήθως έχει Skeletal Mesh: γεωμετρία δεμένη σε οστά. Το εργαστήριό μας χρησιμοποιεί πρωτότυπο αρθρωτό μοντέλο και διαδικαστικές πόζες, όχι αρχείο .uasset.',diagram:['Γεωμετρία','Skeleton · οστά','Pose · τελική στάση'],tip:'Μπορεί να μετακινείται η Capsule χωρίς να αλλάζει η πόζα του Mesh. Αυτό μοιάζει με γλίστρημα.'},
 capsule:{title:'Capsule — το όριο σύγκρουσης',body:'Το ορατό παπούτσι δεν αποφασίζει μόνο του αν χωράς από μια πόρτα. Στον Character χρησιμοποιείται Capsule Component για τις βασικές συγκρούσεις κίνησης. Εδώ το περίγραμμα είναι εποπτικό: δεν υλοποιείται ολόκληρη η φυσική του Unreal.',diagram:['Τοίχος','Capsule','Ορατό Mesh μέσα της'],tip:'Η Capsule δεν είναι κινούμενο μέρος του σώματος.'},
 node:{title:'Node — ένας κόμβος, μια συγκεκριμένη δουλειά',body:'Το Add Movement Input ζητά μετακίνηση. Το Get Actor Forward Vector δίνει κατεύθυνση. Ο πρώτος χρειάζεται εκτέλεση· ο δεύτερος παρέχει δεδομένα όταν ζητηθούν. Δεν εκτελούνται όλοι οι κόμβοι με τον ίδιο τρόπο.',diagram:['Γεγονός','Εντολή','Αποτέλεσμα'],tip:'Πάτησε το ? πάνω σε οποιονδήποτε υποστηριζόμενο κόμβο.'},
 pin:{title:'Pin — η είσοδος ή έξοδος ενός κόμβου',body:'Ένα pin είναι η υποδοχή στην άκρη του κόμβου. Συνδέεις έξοδο προς συμβατή είσοδο. Τα λευκά pins ελέγχουν εκτέλεση. Άλλα pins μεταφέρουν αριθμούς, διανύσματα, Boolean, αναφορές ή πόζες.',diagram:['Έξοδος','Συμβατός τύπος','Είσοδος'],tip:'Ακουμπάς την έξοδο και μετά την είσοδο. Δεν χρειάζεται να κρατάς το δάχτυλο πάνω στο καλώδιο.'},
 event:{title:'Event — πότε ξεκινά κάτι',body:'Πατάς το κουμπί για το σπαθί. Αυτό δημιουργεί ένα γεγονός εισόδου. Το λευκό καλώδιο λέει ποια εντολή ακολουθεί. Η ύπαρξη μιας εντολής πάνω στον καμβά δεν αρκεί για να εκτελεστεί.',diagram:['Πάτημα','IA_Attack · Started','Play Anim Montage'],tip:'Στην εφαρμογή η σκηνή τρέχει συνεχώς. Οι αλλαγές γραφήματος εφαρμόζονται ζωντανά, όχι με τον ίδιο κύκλο Compile/Play του Unreal.'},
 vector:{title:'Vector — τρεις αριθμοί με συγκεκριμένο νόημα',body:'Για το World Direction, το (1, 0, 0) δείχνει προς τον άξονα X. Το (0, 1, 0) προς Y. Το (0, 0, 0) δεν δείχνει πουθενά: γι’ αυτό ο χαρακτήρας δεν μετακινείται. Ένα Vector μπορεί αλλού να σημαίνει θέση ή ταχύτητα — το pin καθορίζει το νόημα.',diagram:['X · μπροστά εδώ','Y · δεξιά εδώ','Z · επάνω στον Unreal'],tip:'Στο Make Vector δοκίμασε X = 0 και Y = 1.'},
 target:{title:'Target — ποιο αντικείμενο δέχεται την εντολή',body:'Δύο πόρτες δεν είναι το ίδιο αντικείμενο. Το Target αποφασίζει ποια θα αλλάξει. Το Add Movement Input χρειάζεται Pawn. Το Set Relative Rotation χρειάζεται Scene Component, εδώ το DoorPivot στον μεντεσέ.',diagram:['Εντολή','Target','Συγκεκριμένο αντικείμενο'],tip:'Το self σημαίνει το αντικείμενο στο πλαίσιο του συγκεκριμένου Blueprint. Εδώ οι προεπιλογές έχουν ήδη ρυθμιστεί για τον εκπαιδευτικό Character.'},
 animgraph:{title:'AnimGraph — πώς θα φαίνεται το σώμα',body:'Το Event Graph δίνει την εντολή «μετακινήσου». Το AnimGraph επιλέγει και συνδυάζει πόζες για το Mesh. Γι’ αυτό τα πόδια μπορεί να μένουν ακίνητα ενώ το σώμα αλλάζει θέση. Οι σύνδεσμοι Pose δεν είναι λευκά καλώδια εκτέλεσης.',diagram:['Velocity → Speed','Blend Space → Pose','Output Pose → Mesh'],tip:'Άνοιξε «AnimGraph» και αφαίρεσε τη σύνδεση προς Output Pose. Μετά κράτησε «Βήμα».'},
 eventgraph:{title:'Event Graph — πότε και τι συμβαίνει',body:'Εδώ συνδέεις γεγονότα και εντολές. Για παράδειγμα: όταν πατηθεί το άλμα, κάλεσε Jump στον Character. Αυτό δεν ορίζει από μόνο του τη στάση των γονάτων στον αέρα.',diagram:['Input Action','Jump','Character Movement'],tip:'Για το ορατό αποτέλεσμα του σκελετού, δες το ξεχωριστό AnimGraph.'},
 animation:{title:'Animation — κίνηση του ορατού σκελετού',body:'Μια κίνηση σπαθιού χρειάζεται ήδη φτιαγμένα δεδομένα animation ή διαδικαστικό έλεγχο οστών. Το Play Anim Montage δεν επινοεί τη χειρονομία: παίζει ένα συγκεκριμένο asset. Εδώ το clip είναι διαδικαστικό και δεμένο στο αρθρωτό εκπαιδευτικό μοντέλο.',diagram:['Έτοιμο clip','Montage / Slot','Τελική πόζα'],tip:'Το σπαθί παραμένει δεμένο στη λαβή του χεριού σε όλη την κίνηση.'},
 slot:{title:'Slot — η θέση όπου μπαίνει το Montage',body:'Μπορεί να κλήθηκε Play Anim Montage, αλλά να μη βλέπεις τίποτα. Χρειάζεται συμβατό Slot στη διαδρομή προς το Output Pose. Στο παράδειγμα χρησιμοποιούμε DefaultSlot. Για χέρια ανεξάρτητα από πόδια υπάρχει και Layered blend per bone με προετοιμασμένο φίλτρο στο spine_01.',diagram:['Play Anim Montage','Slot · DefaultSlot','Output Pose'],tip:'Δοκίμασε το preset «Σπαθί + ανεξάρτητα πόδια».'},
 boolean:{title:'Boolean — μόνο True ή False',body:'Έχεις το κλειδί; Η τιμή HasKey θυμάται Ναι ή Όχι. Το Branch χρησιμοποιεί αυτή την απάντηση, όταν φτάσει σε αυτό η εκτέλεση.',diagram:['HasKey','Branch','True / False'],tip:'Στην πόρτα άλλαξε το «Έχω κλειδί» και ξαναπάτησε το κουμπί.'},
 blueprint:{title:'Blueprint — ένα σύστημα οπτικής λογικής',body:'Δεν είναι απλώς ένα σχεδιάγραμμα που μοιάζει σωστό. Οι τύποι, οι αναφορές, η σειρά εκτέλεσης και το κατάλληλο πλαίσιο καθορίζουν το αποτέλεσμα. Εδώ εκτελείται περιορισμένο, ρητά υλοποιημένο σύνολο κόμβων — όχι ο Unreal μέσα στον browser.',diagram:['Σωστό πλαίσιο','Σωστές συνδέσεις','Παρατήρηση αποτελέσματος'],tip:'Στο «Ελεύθερα» μπορείς να συνδυάσεις όλους τους υλοποιημένους κόμβους, όχι όλους όσους διαθέτει η Epic.'}
};
const tasks={
 walk:{title:'Δώσε ζωή στο πρώτο βήμα',subtitle:'Από ένα πάτημα στη μετακίνηση. Το animation είναι ήδη έτοιμο.',steps:[
 ['Πρόσθεσε το γεγονός εισόδου','Βρες το IA_MoveForward στην παλέτα. Αυτό ακούει το «Βήμα» ή το W.','add','moveInput'],
 ['Πρόσθεσε την εντολή κίνησης','Βρες Add Movement Input. Ο Character υπάρχει ήδη ως προετοιμασμένο Target self.','add','move'],
 ['Πρόσθεσε την κατεύθυνση','Get Actor Forward Vector: δίνει προς τα πού κοιτάζει μπροστά ο Actor. Δεν τον κινεί μόνο του.','add','forward'],
 ['Σύνδεσε το πότε με το τι','IA_MoveForward: Triggered → Add Movement Input: Εκτέλεση. Λευκό σε λευκό.','wire','moveInput','triggered','move','in'],
 ['Δώσε κατεύθυνση στην εντολή','Forward Vector: Return Value → World Direction. Χωρίς κατεύθυνση έχουμε εντολή αλλά κανένα βήμα.','wire','forward','value','move','direction'],
 ['Δώσε το πρόσημο του πατήματος','Action Value → Scale Value. Έτσι Μπροστά = +1 και Πίσω = −1, αντί να χρησιμοποιείται πάντα η σταθερά 1.','wire','moveInput','value','move','scale'],
 ['Απόδειξέ το με κίνηση','Κράτησε «Βήμα» για λίγο και ύστερα «Πίσω». Θα καταγραφεί αποτέλεσμα μόνο όταν ο χαρακτήρας κινηθεί πράγματι και προς τις δύο κατευθύνσεις.','proof','walk']
 ]},
 jump:{title:'Πρόσθεσε άλμα χωρίς να χαλάσεις το περπάτημα',subtitle:'Οι συνδέσεις περπατήματος παραμένουν. Χτίζεις μόνο τη νέα λειτουργία.',steps:[['Πρόσθεσε IA_Jump','Input Action τύπου Boolean. Ακούει το κουμπί Άλμα ή Space.','add','jumpInput'],['Πρόσθεσε Jump','Αυτό ζητά φυσικό άλμα του Character, όχι animation των ποδιών.','add','jump'],['Σύνδεσε το πρώτο πάτημα','IA_Jump: Started → Jump: Εκτέλεση. Δεν χρειάζεται επαναλαμβανόμενο Triggered για αυτό το παράδειγμα.','wire','jumpInput','started','jump','in'],['Πρόσθεσε Stop Jumping','Το αφήνουμε στο γράφημα ώστε το τέλος της εισόδου να είναι σαφές. JumpMaxHoldTime εδώ είναι 0.','add','stopJump'],['Σύνδεσε την απελευθέρωση','Completed → Stop Jumping: Εκτέλεση. Για ακύρωση από απώλεια εστίασης μπορείς να συνδέσεις και Canceled.','wire','jumpInput','completed','stopJump','in'],['Πάτησε Άλμα και παρατήρησε την προσγείωση','Η επιτυχία απαιτεί πραγματική απογείωση και επιστροφή στο έδαφος.','proof','jump']]},
 arms:{title:'Η πρώτη κίνηση με το σπαθί',subtitle:'Το AM_SwordSlash και το DefaultSlot είναι προετοιμασμένα.',steps:[['Πρόσθεσε IA_Attack','Είναι το δικό μας Input Action για το κουμπί Σπαθί.','add','attackInput'],['Πρόσθεσε Play Anim Montage','Διάλεξε το προετοιμασμένο AM_SwordSlash. Το node δεν δημιουργεί κίνηση από το μηδέν.','add','montage'],['Σύνδεσε την αρχή του πατήματος','Started → Εκτέλεση. Ένα πάτημα, μία εκκίνηση montage.','wire','attackInput','started','montage','in'],['Δες το πραγματικό χτύπημα στον αέρα','Πάτησε Σπαθί. Αν το Montage ξεκινά αλλά τα χέρια μένουν ακίνητα, έλεγξε το Slot στο AnimGraph.','proof','arms']]},
 door:{title:'Μία πόρτα, δύο πιθανές διαδρομές',subtitle:'Ο διακόπτης του demo δημιουργεί IA_Interact. Δεν περιλαμβάνεται line trace ή proximity σύστημα.',steps:[['Πρόσθεσε το IA_Interact','Ξεκινά από το κουμπί «Πόρτα» του demo.','add','interactInput'],['Πρόσθεσε ένα Branch','Εδώ χωρίζουμε την εκτέλεση ανάλογα με το αν υπάρχει κλειδί.','add','branch'],['Πρόσθεσε HasKey','Είναι μεταβλητή του δικού μας project, όχι έτοιμη ιδιότητα κάθε Unreal Character.','add','key'],['Σύνδεσε την εκτέλεση','Started → Branch: Εκτέλεση.','wire','interactInput','started','branch','in'],['Σύνδεσε την απάντηση','HasKey → Condition.','wire','key','value','branch','condition'],['Πρόσθεσε την εντολή περιστροφής','Set Relative Rotation, New Rotation: Pitch 0 / Yaw 90 / Roll 0. Αυτή είναι άμεση στροφή.','add','rotate'],['Πρόσθεσε το DoorPivot','Αναφορά στον μεντεσέ — όχι σε τυχαίο αντικείμενο.','add','doorRef'],['Σύνδεσε ποιο αντικείμενο περιστρέφεται','DoorPivot → Target του Set Relative Rotation.','wire','doorRef','value','rotate','target'],['Σύνδεσε τη θετική διαδρομή','True του Branch → Εκτέλεση του Set Relative Rotation.','wire','branch','true','rotate','in'],['Δοκίμασε χωρίς και με κλειδί','Άφησε «Έχω κλειδί» κλειστό και πάτησε Πόρτα. Μετά ενεργοποίησέ το και ξαναπάτησε. Πρέπει να παρατηρηθούν και οι δύο περιπτώσεις.','proof','door']]},
 anim:{title:'Γιατί γλιστρά χωρίς να περπατά;',subtitle:'Το Event Graph μετακινεί το σώμα. Εσύ τώρα χτίζεις τη διαδρομή της πόζας.',steps:[['Διάβασε την ταχύτητα','Πρόσθεσε Get Velocity. Το Target είναι προετοιμασμένο για τον εκπαιδευτικό Character. Στον πραγματικό AnimBP χρειάζεσαι έγκυρη αναφορά στον ιδιοκτήτη.','add','velocity'],['Μετέτρεψε το Vector σε Speed','Πρόσθεσε Vector Length XY. Αγνοεί την κατακόρυφη ταχύτητα του άλματος.','add','lengthXY'],['Σύνδεσε την ταχύτητα','Get Velocity: Return Value → Vector Length XY: A.','wire','velocity','value','lengthXY','vector'],['Πρόσθεσε το Blend Space','Blend Space Player · BS_Locomotion. Το asset περιέχει ήδη Idle στα 0 και Walk στα 250.','add','locomotion'],['Σύνδεσε το Speed','Vector Length XY: Return Value → Speed.','wire','lengthXY','value','locomotion','speed'],['Πρόσθεσε την τελική έξοδο','Output Pose είναι η τελική πόζα για το Mesh. Δεν έχει λευκό execution pin.','add','output'],['Οδήγησε την πόζα στο σώμα','Pose του Blend Space → Result του Output Pose.','wire','locomotion','pose','output','pose'],['Κράτησε Βήμα και δες τα γόνατα','Η ταχύτητα πρέπει να είναι μη μηδενική και η πόζα περπατήματος ενεργή. Δεν αρκεί μόνο να βλέπουμε κόμβους στη σειρά.','proof','anim']]}
};
const transfer={
 legs:['Στον UE 5.8, δημιούργησε Blueprint Class με γονέα Character ή χρησιμοποίησε το Character του template. Έλεγξε ποιος Character ελέγχεται πράγματι από τον Player Controller.','Δημιούργησε IA_MoveForward τύπου Axis1D και IMC_Explorer. W = +1, S με Negate = −1. Εφάρμοσε το Mapping Context στο Enhanced Input Local Player Subsystem του τοπικού παίκτη.','Στο Character Event Graph βάλε IA_MoveForward. Σύνδεσε Triggered στο Add Movement Input, Get Actor Forward Vector στο World Direction και Action Value στο Scale Value.','Για το άλμα, IA_Jump τύπου Boolean: Started → Jump, Completed και Canceled → Stop Jumping. Χρειάζεται έγκυρος Character ως Target.','Compile και Play. Το ορατό περπάτημα εξαρτάται ξεχωριστά από το Skeletal Mesh, το σωστό Anim Class και το AnimGraph.'],
 arms:['Χρειάζεται Skeletal Mesh, συμβατό Skeleton και πραγματικό animation asset κίνησης σπαθιού. Το procedural clip αυτής της σελίδας δεν είναι .uasset.','Δημιούργησε Animation Montage από συμβατό animation και όρισε Slot, π.χ. DefaultGroup.DefaultSlot.','Στο Character Event Graph: IA_Attack τύπου Boolean, Started → Play Anim Montage. Επίλεξε το δικό σου Montage.','Στο AnimGraph του Animation Blueprint πρόσθεσε το αντίστοιχο Slot στη διαδρομή προς Output Pose. Επιβεβαίωσε Animation Mode = Use Animation Blueprint και σωστό Anim Class στο Mesh.','Για χτύπημα άνω σώματος ενώ τα πόδια συνεχίζουν διαφορετική κίνηση, χρησιμοποίησε Layered blend per bone με κατάλληλο φίλτρο στον δικό σου σκελετό. Το όνομα spine_01 του demo δεν ισχύει για κάθε Skeleton.'],
 anim:['Δημιούργησε Animation Blueprint για το Skeleton του χαρακτήρα σου και όρισέ το ως Anim Class στο Skeletal Mesh.','Πάρε έγκυρη αναφορά στον Pawn/Character που ανήκει στο AnimInstance. Στο AnimBP το self είναι AnimInstance — όχι Character. Στο εργαστήριο αυτό το context έχει προετοιμαστεί.','Διάβασε την ταχύτητα του ιδιοκτήτη και υπολόγισε Speed με Vector Length XY. Αποθήκευσέ το σε μεταβλητή με κατάλληλο update workflow του AnimBP ή Property Access· μη συνδέσεις ένα αυθαίρετο Actor self.','Δημιούργησε Blend Space με συμβατά Idle/Walk animations και άξονα Speed. Η λέξη Speed του demo είναι όνομα που δώσαμε στον άξονα του asset.','Σύνδεσε τον Blend Space Player στο Output Pose. Πρόσθεσε Is Falling, Blend Poses by Bool και Jump animation όταν τα βασικά λειτουργούν. Compile και δοκίμασε.'],
 door:['Δημιούργησε BP_Door Actor με Scene Component DoorPivot στο σημείο του μεντεσέ. Κάνε το Mesh παιδί του DoorPivot.','Πρόσθεσε HasKey ως μεταβλητή στο κατάλληλο σύστημα inventory/Character και απόκτησε σωστή αναφορά στην πόρτα. Το demo έχει προετοιμάσει αυτές τις αναφορές.','Η επιλογή της κοντινής πόρτας στον πραγματικό κόσμο χρειάζεται δική σου λογική, π.χ. overlap ή line trace. Το κουμπί του browser δεν την υλοποιεί.','Σύνδεσε το γεγονός αλληλεπίδρασης σε Branch και έλεγξε HasKey. True → Set Relative Rotation του DoorPivot με επιθυμητό Yaw.','Η αλλαγή είναι άμεση. Για ομαλό άνοιγμα, πρόσθεσε ξεχωριστά Timeline και interpolation και έλεγξε τις συγκρούσεις. Αυτά δεν εξομοιώνονται πλήρως εδώ.']
};
window.CBLContent={sources,concepts,tasks,transfer};
})();
