/* Character Blueprint Lab — bounded, explicit educational interpreter. No eval. */
(function(root){'use strict';
const pin=(id,label,type,def,kind)=>({id,label,type,def,kind});
const E=()=>pin('in','Εκτέλεση','exec'),O=()=>pin('out','Συνέχεια','exec'),self=(kind='character')=>pin('target','Target','object','self',kind);
const R={};
function node(id,name,category,scope,ins,outs,help,extra={}){R[id]={id,name,category,scope,ins,outs,help,...extra};}
node('begin','Event BeginPlay','Γεγονότα','event',[],[O()],'Εκτελείται μία φορά όταν ξεκινά η δοκιμή. Η σύνδεση καλωδίου δεν ξαναδημιουργεί αυτό το γεγονός.');
node('tick','Event Tick','Γεγονότα','event',[],[O(),pin('dt','Delta Seconds','float',0)],'Μία ενημέρωση σε κάθε καρέ. Το Delta Seconds είναι ο χρόνος του καρέ, όχι ταχύτητα.');
node('moveInput','IA_MoveForward','Χειρισμός','event',[],[pin('started','Started','exec'),pin('triggered','Triggered','exec'),pin('completed','Completed','exec'),pin('value','Action Value','float',0)],'Input Action δικού μας project, τύπου Axis1D: Μπροστά/W = +1, Πίσω/S = −1. Χωρίς επιπλέον triggers, το Triggered επαναλαμβάνεται όσο κρατάς το πλήκτρο.',{project:true});
for(const [id,name] of [['jumpInput','IA_Jump'],['attackInput','IA_Attack'],['interactInput','IA_Interact']])node(id,name,'Χειρισμός','event',[],[pin('started','Started','exec'),pin('triggered','Triggered','exec'),pin('completed','Completed','exec'),pin('canceled','Canceled','exec'),pin('value','Action Value','bool',false)],'Input Action δικού μας project, τύπου Boolean. Started: αρχή πατήματος. Completed: ολοκλήρωση. Η πραγματική συμπεριφορά Triggered εξαρτάται από τους ορισμένους triggers.',{project:true});
node('move','Add Movement Input','Κίνηση','event',[E(),self('pawn'),pin('direction','World Direction','vector',[0,0,0]),pin('scale','Scale Value','float',1),pin('force','Force','bool',false)],[O()],'Δίνει είσοδο κίνησης στον Pawn. Στον Character το σύστημα κίνησης την καταναλώνει. Δεν δημιουργεί μόνο του animation περπατήματος.');
node('forward','Get Actor Forward Vector','Δεδομένα','both',[self('actor')],[pin('value','Return Value','vector',[1,0,0])],'Δίνει την μπροστινή κατεύθυνση του Actor στον κόσμο. Vector είναι τρεις αριθμοί X, Y, Z — όχι εντολή κίνησης.');
node('right','Get Actor Right Vector','Δεδομένα','both',[self('actor')],[pin('value','Return Value','vector',[0,1,0])],'Η δεξιά κατεύθυνση του χαρακτήρα. Δοκίμασέ τη στη θέση της μπροστινής.');
node('vector','Make Vector','Δεδομένα','both',[pin('x','X','float',1),pin('y','Y','float',0),pin('z','Z','float',0)],[pin('value','Return Value','vector',[1,0,0])],'Συνθέτει τρεις αριθμούς σε Vector. Στον Unreal, Z είναι επάνω. Εδώ η αντιστοίχιση αξόνων γίνεται στον renderer.');
node('float','Make Literal Float','Δεδομένα','both',[pin('value','Value','float',1)],[pin('value','Return Value','float',1)],'Δίνει έναν σταθερό δεκαδικό αριθμό. Δεν εκτελεί κάποια δράση από μόνος του.');
node('multiply','Multiply (Float)','Μαθηματικά','both',[pin('a','A','float',1),pin('b','B','float',1)],[pin('value','Return Value','float',1)],'Πολλαπλασιάζει δύο αριθμούς. B = −1 αντιστρέφει το πρόσημο της κίνησης. Η συσσωρευμένη είσοδος Character κανονικοποιείται όταν ξεπερνά μέτρο 1.');
node('clamp','Clamp (Float)','Μαθηματικά','both',[pin('value','Value','float',0),pin('min','Min','float',0),pin('max','Max','float',1)],[pin('value','Return Value','float',0)],'Περιορίζει αριθμό μεταξύ Min και Max. Δεν αλλάζει από μόνο του την ταχύτητα του Character.');
node('greater','Greater (Float)','Συνθήκες','both',[pin('a','A','float',0),pin('b','B','float',0)],[pin('value','Return Value','bool',false)],'Ρωτά αν το A είναι μεγαλύτερο από το B. Η απάντηση είναι Boolean: True ή False.');
node('bool','Make Literal Bool','Συνθήκες','both',[pin('value','Value','bool',true)],[pin('value','Return Value','bool',true)],'Σταθερή τιμή True/False. Χρήσιμη για να πειραματιστείς με το Branch.');
node('not','NOT Boolean','Συνθήκες','both',[pin('value','A','bool',false)],[pin('value','Return Value','bool',true)],'Αντιστρέφει True και False.');
node('branch','Branch','Ροή','event',[E(),pin('condition','Condition','bool',false)],[pin('true','True','exec'),pin('false','False','exec')],'Εκτελεί μόνο μία από δύο διαδρομές. Το κόκκινο καλώδιο απαντά στην ερώτηση· το λευκό ξεκινά τον έλεγχο.');
node('sequence','Sequence','Ροή','event',[E()],[pin('then0','Then 0','exec'),pin('then1','Then 1','exec')],'Εκτελεί πρώτα την πρώτη διαδρομή και μετά τη δεύτερη. Δεν είναι καθυστέρηση χρόνου. Το εργαστήριο υποστηρίζει δύο εξόδους.');
node('flip','FlipFlop','Ροή','event',[E()],[pin('a','A','exec'),pin('b','B','exec'),pin('isa','Is A','bool',true)],'Εναλλάσσει A και B σε κάθε εκτέλεση. Π.χ. άνοιγμα και κλείσιμο πόρτας. Η κατάσταση επανέρχεται με «Αρχή».');
node('jump','Jump','Κίνηση','event',[E(),self()],[O()],'Ζητά άλμα του Character. Εδώ JumpMaxHoldTime = 0, ένα άλμα, απλοποιημένη βαρύτητα. Δεν αναπαράγει animation από μόνο του.');
node('stopJump','Stop Jumping','Κίνηση','event',[E(),self()],[O()],'Τερματίζει την παρατεταμένη εντολή άλματος. Δεν τηλεμεταφέρει τον χαρακτήρα στο πάτωμα.');
node('montage','Play Anim Montage','Animation','event',[E(),self(),pin('asset','Anim Montage','asset','AM_SwordSlash','montage'),pin('rate','In Play Rate','float',1),pin('section','Start Section Name','string','None')],[O(),pin('duration','Return Value','float',0)],'Ξεκινά το επιλεγμένο Montage. Χρειάζεται συμβατό Skeleton και Slot στο AnimGraph. Εδώ το AM_SwordSlash είναι έτοιμο εκπαιδευτικό clip, όχι αυτόματη δημιουργία animation.',{asset:true});
node('print','Print String','Έλεγχος','event',[E(),pin('text','In String','string','Γεια σου, Άρη!')],[O()],'Γράφει μήνυμα στον ζωντανό έλεγχο. Το χρησιμοποιούμε για να αποδείξουμε ότι πέρασε η εκτέλεση από εδώ.');
node('key','HasKey','Δεδομένα','both',[],[pin('value','HasKey','bool',false)],'Δική μας μεταβλητή του project: έχει ο παίκτης το κλειδί; Η τιμή αλλάζει από τον διακόπτη δοκιμής.',{project:true});
node('doorRef','DoorPivot','Αντικείμενα','both',[],[pin('value','DoorPivot','object','door','scene')],'Αναφορά στο Scene Component που βρίσκεται στον μεντεσέ της πόρτας. Δεν είναι γενικός native κόμβος με όνομα DoorPivot.',{project:true});
node('rotate','Set Relative Rotation','Αντικείμενα','event',[E(),pin('target','Target','object',null,'scene'),pin('rotation','New Rotation','rotator',[0,90,0]),pin('sweep','Sweep','bool',false),pin('teleport','Teleport','bool',false)],[O()],'Αλλάζει αμέσως σχετική περιστροφή ως προς τον γονέα. Στο εργαστήριο υποστηρίζεται Yaw για τον μεντεσέ. Δεν είναι ομαλή περιστροφή Timeline και δεν γίνεται έλεγχος σύγκρουσης.');
node('velocity','Get Velocity','Animation δεδομένα','both',[self('actor')],[pin('value','Return Value','vector',[0,0,0])],'Η τρέχουσα ταχύτητα σε cm/s, σε τρεις άξονες. Άλλο ταχύτητα του σώματος και άλλο animation των ποδιών.');
node('length','Vector Length','Animation δεδομένα','both',[pin('vector','A','vector',[0,0,0])],[pin('value','Return Value','float',0)],'Το μέτρο ενός Vector. Από Velocity παίρνουμε έναν αριθμό Speed. Περιλαμβάνει και κατακόρυφη ταχύτητα.');
node('lengthXY','Vector Length XY','Animation δεδομένα','both',[pin('vector','A','vector',[0,0,0])],[pin('value','Return Value','float',0)],'Μέτρο μόνο στους οριζόντιους άξονες X/Y. Έτσι το άλμα δεν μετριέται ως γρήγορο περπάτημα.');
node('movementRef','Character Movement','Αντικείμενα','both',[],[pin('value','Character Movement','object','movement','movement')],'Αναφορά στο Character Movement Component. Αυτό διαχειρίζεται την κίνηση· δεν είναι το ορατό Mesh.',{project:true});
node('falling','Is Falling','Animation δεδομένα','both',[pin('target','Target','object','movement','movement')],[pin('value','Return Value','bool',false)],'Ρωτά το Movement Component αν ο χαρακτήρας βρίσκεται σε πτώση. Εδώ True όσο το σώμα είναι στον αέρα.');
node('maxSpeed','Set Max Walk Speed','Κίνηση','event',[E(),pin('target','Target','object','movement','movement'),pin('speed','Max Walk Speed','float',250)],[O()],'Θέτει την ιδιότητα Max Walk Speed του Character Movement σε cm/s. Είναι setter ιδιότητας, όχι αλλαγή Play Rate animation.');
node('idle','Sequence Player · Idle','Πόζες','anim',[],[pin('pose','Pose','pose')],'Παίζει το έτοιμο clip αναμονής. Η ακριβής ονομασία του asset εξαρτάται από το project.',{asset:true});
node('locomotion','Blend Space Player · BS_Locomotion','Πόζες','anim',[pin('speed','Speed','float',0)],[pin('pose','Pose','pose')],'Blend Space με άξονα Speed: Idle στα 0, Walk στα 250 cm/s. Το BS_Locomotion είναι asset που έχουμε προετοιμάσει, όχι γενικό native node.',{asset:true});
node('jumpPose','Sequence Player · Jump','Πόζες','anim',[],[pin('pose','Pose','pose')],'Έτοιμη πόζα/κίνηση άλματος. Δεν προκαλεί φυσικό άλμα του Character.',{asset:true});
node('blendBool','Blend Poses by Bool','Πόζες','anim',[pin('condition','Active Value','bool',false),pin('truepose','True Pose','pose'),pin('falsepose','False Pose','pose')],[pin('pose','Pose','pose')],'Επιλέγει πόζα βάσει Boolean. Στην παρούσα προσομοίωση οι χρόνοι blending είναι 0 — άμεση επιλογή.');
node('slot','Slot · DefaultSlot','Πόζες','anim',[pin('source','Source','pose')],[pin('pose','Pose','pose')],'Σημείο του AnimGraph στο οποίο εμφανίζεται το Montage του αντίστοιχου Slot. Χωρίς Slot δεν βλέπεις το χτύπημα, ακόμη κι αν εκτελέστηκε Play Anim Montage.');
node('layer','Layered blend per bone','Πόζες','anim',[pin('base','Base Pose','pose'),pin('blend','Blend Poses 0','pose'),pin('weight','Blend Weights 0','float',1)],[pin('pose','Pose','pose')],'Προετοιμασμένο Branch Filter στο spine_01. Παίρνει κάτω σώμα από Base και άνω σώμα από Blend. Δεν είναι γενικός editor φίλτρων οστών στην παρούσα έκδοση.');
node('output','Output Pose','Πόζες','anim',[pin('pose','Result','pose')],[],'Η τελική πόζα που εμφανίζεται στο ορατό Mesh. Χωρίς συνδεδεμένη Pose βλέπεις τη στάση αναφοράς, παρότι η κάψουλα μπορεί να μετακινείται.');
const copy=v=>JSON.parse(JSON.stringify(v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function make(type,id,x=50,y=50){if(!Object.hasOwn(R,type))throw Error('Άγνωστος κόμβος');return {id,type,x,y,values:Object.fromEntries(R[type].ins.filter(p=>p.def!==undefined).map(p=>[p.id,copy(p.def)]))};}
const graph=()=>({nodes:[],edges:[]});
const outpin=(n,p)=>R[n.type].outs.find(v=>v.id===p),inpin=(n,p)=>R[n.type].ins.find(v=>v.id===p);
function compatible(a,b){if(a.type!==b.type)return false;if(a.type!=='object'||!b.kind||!a.kind)return true;return a.kind===b.kind||(b.kind==='actor'&&['character','pawn'].includes(a.kind))||(b.kind==='pawn'&&a.kind==='character');}
function canConnect(g,from,fp,to,tp){if(from===to)return 'Ο κόμβος δεν μπορεί να συνδεθεί στον εαυτό του.';const a=g.nodes.find(n=>n.id===from),b=g.nodes.find(n=>n.id===to);if(!a||!b)return 'Δεν βρέθηκαν οι κόμβοι.';const x=outpin(a,fp),y=inpin(b,tp);if(!x||!y)return 'Σύνδεσε έξοδο προς είσοδο.';if(!compatible(x,y))return `Το ${x.label} δίνει ${x.type}, ενώ το ${y.label} χρειάζεται ${y.type}${y.kind?' / '+y.kind:''}. Δεν ταιριάζουν.`;const remaining=g.edges.filter(e=>!(y.type!=='exec'&&e.to===to&&e.tp===tp)&&!(x.type==='exec'&&e.from===from&&e.fp===fp));let seen=new Set(),stack=[to];while(stack.length){const id=stack.pop();if(id===from)return 'Το εργαστήριο αποτρέπει κυκλικές συνδέσεις. Loops και latent nodes δεν υποστηρίζονται εδώ.';if(seen.has(id))continue;seen.add(id);for(const e of remaining)if(e.from===id)stack.push(e.to);}return null;}
function connect(g,from,fp,to,tp){const err=canConnect(g,from,fp,to,tp);if(err)throw Error(err);const p=outpin(g.nodes.find(n=>n.id===from),fp);g.edges=g.edges.filter(e=>!(p.type!=='exec'&&e.to===to&&e.tp===tp)&&!(p.type==='exec'&&e.from===from&&e.fp===fp));g.edges.push({id:from+':'+fp+'>'+to+':'+tp,from,fp,to,tp});}
function validate(g,scope){if(!g||!Array.isArray(g.nodes)||!Array.isArray(g.edges)||g.nodes.length>120||g.edges.length>250)throw Error('Μη έγκυρο γράφημα ή υπέρβαση ασφαλούς μεγέθους.');const clean=graph(),ids=new Set();for(const n of g.nodes){if(!n||!Object.hasOwn(R,n.type)||typeof n.id!=='string'||!/^[a-zA-Z0-9_-]{1,50}$/.test(n.id)||ids.has(n.id))throw Error('Άγνωστος ή διπλός κόμβος.');if(scope&&R[n.type].scope!=='both'&&R[n.type].scope!==scope)throw Error('Κόμβος σε λάθος είδος γραφήματος.');if(!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>12000||Math.abs(n.y)>12000)throw Error('Μη έγκυρες συντεταγμένες.');const m=make(n.type,n.id,n.x,n.y);for(const p of R[n.type].ins){const v=n.values?.[p.id];if(v===undefined)continue;if(p.type==='float'&&(!Number.isFinite(v)||Math.abs(v)>1e6))throw Error('Μη έγκυρος αριθμός.');if(p.type==='bool'&&typeof v!=='boolean')throw Error('Μη έγκυρο Boolean.');if(['vector','rotator'].includes(p.type)&&(!Array.isArray(v)||v.length!==3||!v.every(x=>Number.isFinite(x)&&Math.abs(x)<1e6)))throw Error('Μη έγκυρο Vector/Rotator.');if(['asset','string','object'].includes(p.type)&&v!==null&&(typeof v!=='string'||v.length>500))throw Error('Μη έγκυρη τιμή pin.');if(p.type!=='exec'&&p.type!=='pose')m.values[p.id]=copy(v);}ids.add(n.id);clean.nodes.push(m);}if(clean.nodes.filter(n=>n.type==='output').length>1)throw Error('Ένα Output Pose ανά AnimGraph.');for(const e of g.edges){if(!e||typeof e.from!=='string'||typeof e.to!=='string')throw Error('Μη έγκυρο καλώδιο.');const dest=clean.nodes.find(n=>n.id===e.to),src=clean.nodes.find(n=>n.id===e.from),ip=dest&&inpin(dest,e.tp),op=src&&outpin(src,e.fp);if(ip?.type!=='exec'&&clean.edges.some(q=>q.to===e.to&&q.tp===e.tp))throw Error('Δύο πηγές στην ίδια είσοδο δεδομένων.');if(op?.type==='exec'&&clean.edges.some(q=>q.from===e.from&&q.fp===e.fp))throw Error('Μία διαδρομή ανά έξοδο εκτέλεσης. Χρησιμοποίησε Sequence.');connect(clean,e.from,e.fp,e.to,e.tp);}return clean;}
function defaults(){const legs=graph(),arms=graph(),door=graph(),anim=graph();
 legs.nodes=[make('moveInput','input',45,70),make('forward','forward',45,330),make('move','move',415,80)];connect(legs,'input','triggered','move','in');connect(legs,'input','value','move','scale');connect(legs,'forward','value','move','direction');
 arms.nodes=[make('attackInput','attack',55,85),make('montage','montage',430,95)];connect(arms,'attack','started','montage','in');
 door.nodes=[make('interactInput','interact',40,60),make('key','key',50,335),make('branch','branch',360,75),make('doorRef','door',360,365),make('rotate','rotate',685,40),make('print','locked',685,390)];door.nodes[5].values.text='Η πόρτα είναι κλειδωμένη. Χρειάζεσαι το κλειδί.';connect(door,'interact','started','branch','in');connect(door,'key','value','branch','condition');connect(door,'branch','true','rotate','in');connect(door,'door','value','rotate','target');connect(door,'branch','false','locked','in');
 anim.nodes=[make('velocity','velocity',35,55),make('lengthXY','speed',310,55),make('locomotion','locomotion',600,65),make('falling','falling',325,275),make('jumpPose','jumpPose',590,325),make('blendBool','blend',930,75),make('slot','slot',1270,80),make('output','output',1600,80)];connect(anim,'velocity','value','speed','vector');connect(anim,'speed','value','locomotion','speed');connect(anim,'falling','value','blend','condition');connect(anim,'jumpPose','pose','blend','truepose');connect(anim,'locomotion','pose','blend','falsepose');connect(anim,'blend','pose','slot','source');connect(anim,'slot','pose','output','pose');return {legs,arms,door,anim};}
function withJump(g){g=copy(g);for(const id of ['jumpInput','jump','stopJump']){g.nodes=g.nodes.filter(n=>n.id!==id);g.edges=g.edges.filter(e=>e.from!==id&&e.to!==id);}g.nodes.push(make('jumpInput','jumpInput',800,70),make('jump','jump',1175,70),make('stopJump','stopJump',1175,300));connect(g,'jumpInput','started','jump','in');connect(g,'jumpInput','completed','stopJump','in');connect(g,'jumpInput','canceled','stopJump','in');return g;}
function starter(){const g=defaults();g.legs=withJump(g.legs);return g;}
function fresh(){return {x:0,y:0,z:0,vx:0,vy:0,vz:0,speed:0,maxSpeed:250,grounded:true,jumpHeld:false,inputIgnored:false,hasKey:false,doorAngle:0,montage:null,montageTime:0,montageRate:1,pose:{walk:0,jump:0,attack:0},phase:0,travel:0,jumps:0,attacks:0,opened:0,locked:0,prints:0};}
class Engine{
 constructor(graphs){this.graphs=graphs||defaults();this.world=fresh();this.controls={move:0,jump:false,attack:false,interact:false};this.previous={...this.controls};this.time=0;this.signals={};this.trace=[];this.logs=[];this.memory={};this.error='';this.paused=false;this.lastPrint={};this.actions={};this.restart();}
 log(text,type='info'){if(this.logs.at(-1)?.text===text&&this.time-this.logs.at(-1).time<.8)return;this.logs.push({text,type,time:this.time});if(this.logs.length>60)this.logs.shift();}
 mark(key,id){this.signals[key+':'+id]=this.time;this.trace.push({key,id,time:this.time});if(this.trace.length>100)this.trace.shift();}
 input(g,n,id,key,seen){const e=g.edges.find(e=>e.to===n.id&&e.tp===id);if(e){this.signals[key+':'+e.id]=this.time;return this.value(g,e.from,e.fp,key,seen);}const p=inpin(n,id);return n.values?.[id]??p?.def;}
 value(g,id,pid,key,seen=new Set()){if(seen.size>100||seen.has(id))throw Error('Κυκλική εξάρτηση δεδομένων.');seen=new Set(seen);seen.add(id);const n=g.nodes.find(n=>n.id===id);if(!n)throw Error('Λείπει κόμβος δεδομένων.');this.mark(key,id);const get=p=>this.input(g,n,p,key,seen),w=this.world;switch(n.type){case 'moveInput':return this.controls.move;case 'jumpInput':return this.controls.jump;case 'attackInput':return this.controls.attack;case 'interactInput':return this.controls.interact;case 'tick':return this.dt;case 'forward':this.require(get('target'),'self');return [1,0,0];case 'right':this.require(get('target'),'self');return [0,1,0];case 'vector':return [get('x'),get('y'),get('z')];case 'float':case 'bool':return get('value');case 'multiply':return get('a')*get('b');case 'clamp':return clamp(get('value'),Math.min(get('min'),get('max')),Math.max(get('min'),get('max')));case 'greater':return get('a')>get('b');case 'not':return !get('value');case 'key':return w.hasKey;case 'doorRef':return 'door';case 'movementRef':return 'movement';case 'velocity':this.require(get('target'),'self');return [w.vx,w.vy,w.vz];case 'length':return Math.hypot(...get('vector'));case 'lengthXY':return Math.hypot(...get('vector').slice(0,2));case 'falling':this.require(get('target'),'movement');return !w.grounded;case 'montage':return this.memory[key+':'+id+':duration']||0;case 'flip':return !!this.memory[key+':'+id+':last'];default:throw Error('Ο κόμβος δεν παρέχει αυτό το είδος δεδομένων.');}}
 require(v,expected){if(v!==expected)throw Error('Λάθος ή κενό Target. Χρειάζεται '+(expected==='self'?'ο Character σου.':expected==='door'?'το DoorPivot.':'το Character Movement Component.'));}
 output(g,n,p,key,budget){for(const e of g.edges.filter(e=>e.from===n.id&&e.fp===p)){this.signals[key+':'+e.id]=this.time;this.execute(g,e.to,key,budget);}}
 execute(g,id,key,budget={n:0}){if(++budget.n>200)throw Error('Σταμάτησα υπερβολικά μεγάλη αλυσίδα εκτέλεσης.');const n=g.nodes.find(n=>n.id===id);if(!n)return;const w=this.world,get=p=>this.input(g,n,p,key,new Set());this.mark(key,id);this.actions[key+':'+n.type]=(this.actions[key+':'+n.type]||0)+1;let out='out';switch(n.type){case 'move':{this.require(get('target'),'self');const d=get('direction'),s=get('scale');if(!Array.isArray(d)||d.length!==3||!d.every(Number.isFinite)||!Number.isFinite(s))throw Error('Χρειάζεται έγκυρο World Direction και Scale Value.');if(!w.inputIgnored||get('force'))this.pending=this.pending.map((v,i)=>v+d[i]*s);break;}case 'jump':this.require(get('target'),'self');w.jumpHeld=true;if(w.grounded){w.vz=430;w.grounded=false;w.jumps++;}break;case 'stopJump':this.require(get('target'),'self');w.jumpHeld=false;break;case 'maxSpeed':this.require(get('target'),'movement');w.maxSpeed=clamp(get('speed'),0,1200);break;case 'montage':{this.require(get('target'),'self');let r=get('rate');if(get('asset')!=='AM_SwordSlash'||r<=0||get('section')!=='None'){this.memory[key+':'+id+':duration']=0;throw Error('Υποστηρίζεται AM_SwordSlash, θετικό Play Rate και Section None.');}w.montage='AM_SwordSlash';w.montageTime=0;w.montageRate=clamp(r,.1,5);w.attacks++;this.memory[key+':'+id+':duration']=1.1/w.montageRate;break;}case 'branch':{const cond=!!get('condition');out=cond?'true':'false';this.memory[key+':branch']=cond;if(!cond&&key==='door'){w.locked++;this.log('False → η πόρτα μένει κλειστή.','branch');}break;}case 'sequence':this.output(g,n,'then0',key,budget);this.output(g,n,'then1',key,budget);return;case 'flip':{const v=!this.memory[key+':'+id];this.memory[key+':'+id]=v;this.memory[key+':'+id+':last']=v;out=v?'a':'b';break;}case 'print':{const text=String(get('text'));if(!this.lastPrint[key+id]||this.time-this.lastPrint[key+id]>.8){this.log(text,'print');this.lastPrint[key+id]=this.time;}w.prints++;break;}case 'rotate':{this.require(get('target'),'door');const r=get('rotation');if(r[0]||r[2])throw Error('Εδώ υποστηρίζεται μόνο Yaw. Θέσε Pitch και Roll σε 0.');if(get('sweep'))throw Error('Το rotational Sweep δεν υποστηρίζεται από το εργαστήριο.');w.doorAngle=clamp(r[1],-180,180);if(Math.abs(w.doorAngle)>60)w.opened++;break;}default:throw Error('Ο κόμβος αυτός δεν είναι εκτελέσιμη εντολή.');}this.output(g,n,out,key,budget);}
 event(type,port){for(const key of ['legs','arms','door']){const g=this.graphs[key];for(const n of g.nodes.filter(n=>n.type===type)){this.mark(key,n.id);try{this.output(g,n,port,key,{n:0});}catch(e){this.error=e.message;this.log(e.message,'error');}}}}
 restart(){const key=this.world.hasKey;this.world=fresh();this.world.hasKey=key;this.memory={};this.actions={};this.previous={move:0,jump:false,attack:false,interact:false};this.controls={...this.previous};this.pending=[0,0,0];this.error='';this.event('begin','out');}
 pose(g,id,key,seen=new Set()){if(seen.has(id)||seen.size>80)return {walk:0,jump:0,attack:0};seen=new Set(seen);seen.add(id);const n=g.nodes.find(n=>n.id===id);if(!n)return {walk:0,jump:0,attack:0};this.mark(key,id);const child=p=>{const e=g.edges.find(e=>e.to===id&&e.tp===p);if(e){this.signals[key+':'+e.id]=this.time;return this.pose(g,e.from,key,seen);}return {walk:0,jump:0,attack:0};},get=p=>this.input(g,n,p,key,new Set());switch(n.type){case 'idle':return {walk:0,jump:0,attack:0};case 'locomotion':return {walk:clamp(Math.abs(get('speed'))/250,0,1.8),jump:0,attack:0};case 'jumpPose':return {walk:0,jump:1,attack:0};case 'blendBool':return child(get('condition')?'truepose':'falsepose');case 'slot':{const a=child('source');return this.world.montage?{walk:0,jump:0,attack:1}:a;}case 'layer':{const a=child('base'),b=child('blend'),v=clamp(get('weight'),0,1);return {walk:a.walk,jump:a.jump,attack:b.attack*v};}case 'output':return child('pose');default:return {walk:0,jump:0,attack:0};}}
 update(dt){if(this.paused)return;dt=clamp(dt,0,.045);this.dt=dt;this.time+=dt;this.pending=[0,0,0];this.error='';this.event('tick','out');for(const [key,type] of [['move','moveInput'],['jump','jumpInput'],['attack','attackInput'],['interact','interactInput']]){const now=this.controls[key],last=this.previous[key];if(now&&!last)this.event(type,'started');if(now)this.event(type,'triggered');if(!now&&last)this.event(type,'completed');}this.previous={...this.controls};const w=this.world,l=Math.hypot(this.pending[0],this.pending[1]),scale=l>1?1/l:1;const vx=this.pending[0]*scale*w.maxSpeed,vy=this.pending[1]*scale*w.maxSpeed;w.vx=vx;w.vy=vy;w.speed=Math.hypot(vx,vy);w.x+=vx*dt;w.y+=vy*dt;w.travel+=w.speed*dt;if(!w.grounded){w.vz-=980*dt;w.z+=w.vz*dt;if(w.z<=0){w.z=0;w.vz=0;w.grounded=true;}}if(w.montage){w.montageTime+=dt*w.montageRate;if(w.montageTime>1.1)w.montage=null;}try{const g=this.graphs.anim,n=g.nodes.find(n=>n.type==='output');w.pose=n?this.pose(g,n.id,'anim'):{walk:0,jump:0,attack:0};}catch(e){w.pose={walk:0,jump:0,attack:0};this.error=e.message;this.log(e.message,'error');}w.phase+=dt*7*Math.max(.3,w.pose.walk);}
 cancel(){this.controls={move:0,jump:false,attack:false,interact:false};for(const type of ['jumpInput','attackInput','interactInput'])this.event(type,'canceled');}
}
root.CBL={R,pin,make,graph,copy,connect,canConnect,compatible,validate,defaults,withJump,starter,Engine,clamp};if(typeof module!=='undefined')module.exports=root.CBL;
})(typeof window==='undefined'?globalThis:window);
