'use strict';const assert=require('node:assert/strict');const C=require('../src/core.js');const {R,make,defaults,graph,connect,canConnect,validate,Engine,withJump,starter,blank}=C;let passed=0;const names=[];
function test(name,fn){try{fn();passed++;names.push(name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
function fresh(){return new Engine(defaults());}function run(e,n=60,dt=1/60){for(let i=0;i<n;i++)e.update(dt);return e.world;}function tap(e,key){e.controls[key]=true;e.update(1/60);e.controls[key]=false;e.update(1/60);}
function basic(...types){return {nodes:types.map((t,i)=>make(t,t,40+i*300,60)),edges:[]};}
test('39 explicit implemented types',()=>assert.equal(Object.keys(R).length,39));
for(const [key,g] of Object.entries(defaults()))test('Default '+key+' validates',()=>assert.equal(validate(g,key==='anim'?'anim':'event').edges.length,g.edges.length));
test('Default movement has no auto input',()=>assert.equal(run(fresh()).x,0));
test('Blank project needs Blueprint connections before character actions',()=>{const e=new Engine(blank());e.controls.move=1;e.controls.jump=true;e.controls.attack=true;run(e);assert.equal(e.world.x,0);assert.equal(e.world.z,0);assert.equal(e.world.attacks,0);assert.equal(e.world.pose.walk,0);});
test('Positive input moves forward',()=>{let e=fresh();e.controls.move=1;assert.ok(run(e).x>240);});
test('Negative input moves backward',()=>{let e=fresh();e.controls.move=-1;assert.ok(run(e).x< -240);});
test('No exec connection means no movement',()=>{let e=fresh();e.graphs.legs.edges=e.graphs.legs.edges.filter(x=>x.tp!=='in');e.controls.move=1;assert.equal(run(e).x,0);});
test('No world direction means no movement',()=>{let e=fresh();e.graphs.legs.edges=e.graphs.legs.edges.filter(x=>x.tp!=='direction');e.controls.move=1;assert.equal(run(e).x,0);});
test('Zero scale means no movement',()=>{let e=fresh();e.graphs.legs.edges=e.graphs.legs.edges.filter(x=>x.tp!=='scale');e.graphs.legs.nodes.find(n=>n.type==='move').values.scale=0;e.controls.move=1;assert.equal(run(e).x,0);});
test('Release stops movement',()=>{let e=fresh();e.controls.move=1;run(e);let x=e.world.x;e.controls.move=0;assert.equal(run(e).x,x);});
test('Pause stops world time',()=>{let e=fresh();e.paused=true;e.controls.move=1;assert.equal(run(e).x,0);});
test('Input ignored without Force',()=>{let e=fresh();e.world.inputIgnored=true;e.controls.move=1;assert.equal(run(e).x,0);});
test('Force flag explicitly overrides ignored input',()=>{let e=fresh();e.world.inputIgnored=true;e.graphs.legs.nodes.find(n=>n.type==='move').values.force=true;e.controls.move=1;assert.ok(run(e).x>0);});
test('Data input accepts one source and replaces old',()=>{let g=defaults().legs;g.nodes.push(make('right','right'));connect(g,'right','value','move','direction');assert.equal(g.edges.filter(e=>e.tp==='direction').length,1);});
test('Data fanout allowed',()=>{let g=basic('float','multiply','clamp');connect(g,'float','value','multiply','a');connect(g,'float','value','clamp','value');assert.equal(g.edges.length,2);});
test('Completed and Canceled share exec input',()=>{const g=withJump(defaults().legs);assert.equal(g.edges.filter(x=>x.to==='stopJump').length,2);assert.equal(validate(g,'event').edges.filter(x=>x.to==='stopJump').length,2);});
test('Exec output reconnect replaces branch',()=>{let g=basic('begin','print','jump');connect(g,'begin','out','print','in');connect(g,'begin','out','jump','in');assert.equal(g.edges.length,1);assert.equal(g.edges[0].to,'jump');});
test('Invalid vector to Boolean rejected',()=>{let g=basic('forward','branch');assert.ok(canConnect(g,'forward','value','branch','condition'));});
test('Wrong object kind rejected',()=>{let g=basic('movementRef','rotate');assert.ok(canConnect(g,'movementRef','value','rotate','target'));});
test('Self cycle rejected',()=>{let g=basic('multiply');assert.ok(canConnect(g,'multiply','value','multiply','a'));});
test('Indirect cycle rejected',()=>{let g=basic('multiply','clamp');connect(g,'multiply','value','clamp','value');assert.ok(canConnect(g,'clamp','value','multiply','a'));});
test('Unknown pin rejected',()=>{let g=basic('begin','print');assert.ok(canConnect(g,'begin','bogus','print','in'));});
test('Jump preset rises',()=>{let e=fresh();e.graphs.legs=withJump(e.graphs.legs);tap(e,'jump');assert.ok(e.world.z>0);});
test('Starter character jumps while the walk lesson stays isolated',()=>{const e=new Engine(starter());tap(e,'jump');assert.ok(e.world.z>0);assert.equal(e.world.jumps,1);assert.equal(defaults().legs.nodes.some(n=>n.type==='jump'),false);});
test('Jump returns to floor',()=>{let e=fresh();e.graphs.legs=withJump(e.graphs.legs);tap(e,'jump');assert.equal(run(e,100).z,0);assert.equal(e.world.grounded,true);});
test('Jump stops on Completed',()=>{let e=fresh();e.graphs.legs=withJump(e.graphs.legs);tap(e,'jump');assert.equal(e.world.jumpHeld,false);});
test('Jump Canceled executes StopJump',()=>{let e=fresh();e.graphs.legs=withJump(e.graphs.legs);e.controls.jump=true;e.update(.01);e.cancel();assert.equal(e.world.jumpHeld,false);});
test('No second jump in air',()=>{let e=fresh();e.graphs.legs=withJump(e.graphs.legs);tap(e,'jump');tap(e,'jump');assert.equal(e.world.jumps,1);});
test('Holding Started triggers once',()=>{let e=fresh();e.controls.attack=true;run(e,80);assert.equal(e.world.attacks,1);});
test('Sword montage reaches Slot',()=>{let e=fresh();tap(e,'attack');assert.equal(e.world.pose.attack,1);});
test('Montage without Slot cannot animate',()=>{let e=fresh();connect(e.graphs.anim,'blend','pose','output','pose');tap(e,'attack');assert.ok(e.world.montage);assert.equal(e.world.pose.attack,0);});
test('Montage completes',()=>{let e=fresh();tap(e,'attack');assert.equal(run(e,100).montage,null);});
test('Full-body montage overrides walk pose',()=>{let e=fresh();e.controls.move=1;tap(e,'attack');assert.equal(e.world.pose.walk,0);assert.ok(e.world.speed>0);});
test('Empty AnimGraph keeps translation but no limb pose',()=>{let e=fresh();e.graphs.anim=graph();e.controls.move=1;run(e);assert.ok(e.world.x>0);assert.equal(e.world.pose.walk,0);});
test('AnimGraph disconnected output no walk',()=>{let e=fresh();e.graphs.anim.edges=e.graphs.anim.edges.filter(x=>x.to!=='output');e.controls.move=1;run(e);assert.equal(e.world.pose.walk,0);});
test('Layered per-bone preserves lower body',()=>{let e=fresh(),g=e.graphs.anim;g.nodes.push(make('layer','layer'));connect(g,'blend','pose','layer','base');connect(g,'slot','pose','layer','blend');connect(g,'layer','pose','output','pose');e.controls.move=1;tap(e,'attack');assert.ok(e.world.pose.walk>0);assert.equal(e.world.pose.attack,1);});
test('Key absent executes only False',()=>{let e=fresh();tap(e,'interact');assert.equal(e.world.doorAngle,0);assert.equal(e.world.locked,1);assert.equal(e.world.opened,0);});
test('Key present executes only True',()=>{let e=fresh();e.world.hasKey=true;tap(e,'interact');assert.equal(e.world.doorAngle,90);assert.equal(e.world.locked,0);});
test('Missing door Target errors safely',()=>{let e=fresh();e.graphs.door.edges=e.graphs.door.edges.filter(x=>x.tp!=='target');e.world.hasKey=true;tap(e,'interact');assert.equal(e.world.doorAngle,0);assert.ok(e.logs.some(l=>/Target/.test(l.text)));});
test('Rotational Sweep unsupported clearly',()=>{let e=fresh();e.graphs.door.nodes.find(n=>n.type==='rotate').values.sweep=true;e.world.hasKey=true;tap(e,'interact');assert.equal(e.world.doorAngle,0);assert.ok(e.logs.some(l=>/Sweep/.test(l.text)));});
test('Reset deterministic and preserves test key',()=>{let e=fresh();e.world.hasKey=true;e.controls.move=1;run(e);e.restart();assert.equal(e.world.x,0);assert.equal(e.world.hasKey,true);assert.equal(e.controls.move,0);});
test('BeginPlay print runs only once per restart',()=>{let e=fresh();e.graphs.arms=basic('begin','print');connect(e.graphs.arms,'begin','out','print','in');e.restart();assert.equal(run(e).prints,1);e.restart();assert.equal(e.world.prints,1);});
test('Sequence completes Then0 before Then1',()=>{let e=fresh(),g=basic('begin','sequence','print');g.nodes.push(make('print','second'));g.nodes[2].values.text='first';g.nodes[3].values.text='second';connect(g,'begin','out','sequence','in');connect(g,'sequence','then0','print','in');connect(g,'sequence','then1','second','in');e.graphs.arms=g;e.restart();assert.deepEqual(e.logs.slice(-2).map(l=>l.text),['first','second']);});
test('Make Vector offers real alternative lateral movement',()=>{let e=fresh(),g=e.graphs.legs;g.nodes.push(make('vector','vec'));g.nodes.at(-1).values={x:0,y:1,z:0};connect(g,'vec','value','move','direction');e.controls.move=1;run(e);assert.equal(e.world.x,0);assert.ok(e.world.y>240);});
test('Float multiplication reverses movement',()=>{let e=fresh(),g=e.graphs.legs;g.nodes.push(make('multiply','mul'));g.nodes.at(-1).values.b=-1;connect(g,'input','value','mul','a');connect(g,'mul','value','move','scale');e.controls.move=1;assert.ok(run(e).x<0);});
test('Movement magnitude capped rather than double speed',()=>{let e=fresh(),g=e.graphs.legs;g.edges=g.edges.filter(x=>x.tp!=='scale');g.nodes.find(n=>n.type==='move').values.scale=10;e.controls.move=1;assert.equal(run(e).speed,250);});
test('Max Walk Speed property affects travel',()=>{let e=fresh(),g=basic('begin','maxSpeed');g.nodes[1].values.speed=500;connect(g,'begin','out','maxSpeed','in');e.graphs.arms=g;e.restart();e.controls.move=1;assert.equal(run(e).speed,500);});
test('Malformed graph rejected',()=>assert.throws(()=>validate({nodes:'bad',edges:[]})));
test('Unknown registry type rejected',()=>assert.throws(()=>validate({nodes:[{id:'x',type:'__proto__',x:0,y:0}],edges:[]})));
test('Duplicate id rejected',()=>{let g=basic('float');g.nodes.push({...g.nodes[0]});assert.throws(()=>validate(g));});
test('Multiple Output Pose rejected',()=>{let g=basic('output');g.nodes.push(make('output','out2'));assert.throws(()=>validate(g));});
test('NaN pin rejected',()=>{let g=basic('float');g.nodes[0].values.value=NaN;assert.throws(()=>validate(g));});
test('Bad vector dimensions rejected',()=>{let g=basic('move');g.nodes[0].values.direction=[1,2];assert.throws(()=>validate(g));});
test('Boolean string rejected',()=>{let g=basic('bool');g.nodes[0].values.value='false';assert.throws(()=>validate(g));});
test('Anim node in EventGraph rejected',()=>assert.throws(()=>validate(basic('slot'),'event')));
test('Exec node in AnimGraph rejected',()=>assert.throws(()=>validate(basic('begin'),'anim')));
test('Out of range import coordinates rejected',()=>{let g=basic('float');g.nodes[0].x=999999;assert.throws(()=>validate(g));});
test('Null edge rejected',()=>{let g=basic('begin');g.edges=[null];assert.throws(()=>validate(g));});
test('Excess nodes rejected',()=>{let g=graph();for(let i=0;i<121;i++)g.nodes.push(make('float','x'+i));assert.throws(()=>validate(g));});
test('Exec fanout import rejected, not silently replaced',()=>{let g=basic('begin','print','jump');g.edges=[{from:'begin',fp:'out',to:'print',tp:'in'},{from:'begin',fp:'out',to:'jump',tp:'in'}];assert.throws(()=>validate(g));});
console.log(JSON.stringify({passed,failed:process.exitCode?true:false,tests:names},null,2));
