/* Dungeon Mentor — instructional subset, not an Unreal runtime. No dependencies. */
(function(root){
'use strict';
const BASE='https://dev.epicgames.com/documentation/en-us/unreal-engine/';
const SOURCES={movement:BASE+'BlueprintAPI/Pawn/Input/AddMovementInput',input:BASE+'enhanced-input-in-unreal-engine',visibility:BASE+'BlueprintAPI/Rendering/SetVisibility',rotation:BASE+'BlueprintAPI/Transformation/SetRelativeRotation',modeling:BASE+'modeling-tools-in-unreal-engine',uv:BASE+'uv-editor-in-unreal-engine',materials:BASE+'essential-unreal-engine-material-concepts',character:BASE+'understanding-networked-movement-in-the-character-movement-component-for-unreal-engine',debug:BASE+'blueprint-debugging-example-in-unreal-engine',best:BASE+'blueprint-best-practices-in-unreal-engine'};
const p=(id,label,type,value)=>({id,label,type,value});
const exin=p('in','', 'exec'), exout=p('out','', 'exec');
const NODES={
 begin:{title:'Event BeginPlay',kind:'event',subtitle:'Όταν ξεκινά η δοκιμή',ins:[],outs:[exout],why:'Ξεκινά μία φορά για αυτό το αντικείμενο σε κάθε νέα δοκιμή. Η σύνδεση μόνη της δεν εκτελεί κάτι.',source:SOURCES.debug},
 input:{title:'IA_MoveForward',kind:'event',subtitle:'Enhanced Input · Axis1D',ins:[],outs:[p('triggered','Triggered','exec'),p('value','Action Value','float')],why:'Δικό μας Input Action, όχι προκαθορισμένο όνομα της Epic. W = +1, S = −1. Χωρίς πρόσθετους triggers, το Triggered επαναλαμβάνεται όσο υπάρχει είσοδος. Το Mapping Context είναι ήδη προετοιμασμένο στο εργαστήριο.',source:SOURCES.input},
 interact:{title:'IA_Interact',kind:'event',subtitle:'Enhanced Input · Digital (bool)',ins:[],outs:[p('started','Started','exec')],why:'Δικό μας Input Action. Το E ή το κουμπί «Αλληλεπίδραση» ξεκινά ένα γεγονός μία φορά σε κάθε πάτημα. Εδώ ελέγχουμε συγκεκριμένη πόρτα, όχι σύστημα ανίχνευσης κοντινών αντικειμένων.',source:SOURCES.input},
 print:{title:'Print String',kind:'action',subtitle:'Γράψε στο ίχνος εκτέλεσης',ins:[exin,p('text','In String','string','Γεια σου, Άρη!')],outs:[exout],why:'Εμφανίζει την τιμή In String όταν φτάσει η εκτέλεση εδώ. Το εργαστήριο δείχνει το μήνυμα στην κονσόλα του· οι προχωρημένες είσοδοι του Unreal δεν προσομοιώνονται.',source:SOURCES.debug},
 forward:{title:'Get Actor Forward Vector',kind:'pure',subtitle:'Προς τα πού κοιτάζει;',ins:[p('target','Target','actor','self')],outs:[p('value','Return Value','vector')],why:'Δίνει την παγκόσμια κατεύθυνση του τοπικού +X του Actor, όχι θέση ούτε ταχύτητα. Ο χαρακτήρας εδώ κοιτάζει σταθερά προς +X. Pure node: υπολογίζεται όταν ζητηθεί η τιμή του.'},
 vector:{title:'Make Vector',kind:'pure',subtitle:'Τρεις τιμές → μία κατεύθυνση',ins:[p('x','X','float',1),p('y','Y','float',0),p('z','Z','float',0)],outs:[p('value','Return Value','vector')],why:'Συνδυάζει X, Y, Z. Στο Unreal το Z είναι επάνω. Το (1,0,0) δείχνει προς +X. Το (0,0,0) δεν δίνει κατεύθυνση.'},
 move:{title:'Add Movement Input',kind:'action',subtitle:'Target is Pawn',ins:[exin,p('target','Target','pawn','self'),p('direction','World Direction','vector',[0,0,0]),p('scale','Scale Value','float',1),p('force','Force','bool',false)],outs:[exout],why:'Προσθέτει επιθυμητή κίνηση, δεν τηλεμεταφέρει. Ο Character έχει σύστημα που καταναλώνει αυτή την είσοδο. Απλός Pawn δεν περπατά αυτόματα. Εδώ προσομοιώνουμε επίπεδη κίνηση, όχι πλήρες Character Movement.',source:SOURCES.movement},
 branch:{title:'Branch',kind:'flow',subtitle:'Έλεγχος μιας συνθήκης',ins:[exin,p('condition','Condition','bool',false)],outs:[p('true','True','exec'),p('false','False','exec')],why:'Όταν φτάσει εκτέλεση, διαβάζει τη Condition και ακολουθεί μόνο μία έξοδο. Η κόκκινη τιμή δεν είναι καλώδιο εκτέλεσης.'},
 key:{title:'Get HasKey',kind:'pure',subtitle:'Μεταβλητή του project · Boolean',ins:[],outs:[p('value','HasKey','bool')],why:'Δική μας μεταβλητή, όχι ενσωματωμένο node με αυτό το όνομα. Θυμάται αν υπάρχει κλειδί. Άλλαξέ την από τον διακόπτη «Έχω κλειδί» στη σκηνή.'},
 torch:{title:'TorchLight_A',kind:'pure',subtitle:'Αναφορά · PointLight Component',ins:[],outs:[p('value','TorchLight_A','scene')],why:'Αναφορά στο αριστερό φως. Δεν ανάβει τίποτα από μόνη της. Είναι η απάντηση στην ερώτηση «ποιο αντικείμενο;».'},
 torchB:{title:'TorchLight_B',kind:'pure',subtitle:'Αναφορά · PointLight Component',ins:[],outs:[p('value','TorchLight_B','scene')],why:'Αναφορά στο δεξί φως. Η επιλογή στόχου είναι ουσιαστική: δεν πρέπει να αλλάζουν και τα δύο φώτα μαζί.'},
 door:{title:'DoorPivot',kind:'pure',subtitle:'Αναφορά · Scene Component',ins:[],outs:[p('value','DoorPivot','scene')],why:'Το σημείο περιστροφής στον μεντεσέ. Η ξύλινη πόρτα είναι παιδί του. Η δική μας μεταβλητή αναφοράς δεν είναι γενικό έτοιμο εργαλείο της Epic.'},
 visible:{title:'Set Visibility',kind:'action',subtitle:'Target is Scene Component',ins:[exin,p('target','Target','scene',null),p('visible','New Visibility','bool',true),p('children','Propagate to Children','bool',false)],outs:[exout],why:'Αλλάζει την ορατότητα του συγκεκριμένου component. Χρειάζεται σωστό Target και εκτέλεση. Το φως Α είναι σβηστό στην αρχή κάθε δοκιμής.',source:SOURCES.visibility},
 rotate:{title:'Set Relative Rotation',kind:'action',subtitle:'Target is Scene Component',ins:[exin,p('target','Target','scene',null),p('rotation','New Rotation','rotator',[0,90,0])],outs:[exout],why:'Ορίζει άμεσα τη στροφή σε σχέση με τον γονέα. Δεν δημιουργεί ομαλό animation. Εδώ υποστηρίζεται Yaw στον DoorPivot. Sweep / Teleport / Hit Result δεν προσομοιώνονται. Στο Unreal το rotational sweep δεν υποστηρίζεται.',source:SOURCES.rotation},
 rotator:{title:'Make Rotator',kind:'pure',subtitle:'Μοίρες: Roll, Pitch, Yaw',ins:[p('roll','Roll','float',0),p('pitch','Pitch','float',0),p('yaw','Yaw','float',90)],outs:[p('value','Return Value','rotator')],why:'Συνθέτει γωνίες σε μοίρες. Το Yaw περιστρέφει γύρω από τον κατακόρυφο άξονα Z του Unreal. Το εργαστήριο πόρτας εφαρμόζει μόνο Yaw.'},
};
const clone=x=>JSON.parse(JSON.stringify(x));
const nid=()=> 'n'+Math.random().toString(36).slice(2,10);
function node(type,x=80,y=80,id=nid()){const d=NODES[type];if(!Object.hasOwn(NODES,type))throw Error('Άγνωστος τύπος κόμβου');return {id,type,x,y,values:Object.fromEntries(d.ins.filter(a=>a.type!=='exec').map(a=>[a.id,clone(a.value??null)]))};}
function edge(a,ap,b,bp){return {id:nid(),from:a,out:ap,to:b,in:bp};}
function compatible(a,b){return a===b || (a==='pawn' && b==='actor');}
function validateConnection(g,e){
 const a=g.nodes.find(n=>n.id===e.from),b=g.nodes.find(n=>n.id===e.to);
 if(!a||!b)return 'Δεν βρέθηκε ο κόμβος της σύνδεσης.';
 const out=NODES[a.type].outs.find(p=>p.id===e.out),inp=NODES[b.type].ins.find(p=>p.id===e.in);
 if(!out||!inp)return 'Σύνδεσε μία έξοδο στα δεξιά με μία είσοδο στα αριστερά.';
 if(a.id===b.id)return 'Δεν συνδέουμε τον κόμβο με τον εαυτό του σε αυτό το εργαστήριο.';
 if(!compatible(out.type,inp.type))return `Ασυμβατότητα: ${out.type} → ${inp.type}. Η εκτέλεση, οι αριθμοί και οι κατευθύνσεις έχουν διαφορετικό ρόλο.`;
 if(g.edges.some(x=>x.to===e.to&&x.in===e.in&&x.id!==e.id))return 'Αυτή η είσοδος έχει ήδη πηγή. Διάγραψε πρώτα το υπάρχον καλώδιο.';
 if(out.type==='exec'&&g.edges.some(x=>x.from===e.from&&x.out===e.out&&x.id!==e.id))return 'Η έξοδος εκτέλεσης έχει ήδη σύνδεση. Για διαδοχικές εντολές σύνδεσε την επόμενη έξοδο.';
 const seen=new Set();function reaches(id){if(id===e.from)return true;if(seen.has(id))return false;seen.add(id);return g.edges.filter(x=>x.from===id&&x.id!==e.id).some(x=>reaches(x.to));}
 if(reaches(e.to))return 'Αυτό δημιουργεί κύκλο. Το εκπαιδευτικό εργαστήριο απορρίπτει κύκλους· δεν είναι γενικός περιορισμός όλων των Blueprints.';
 return null;
}
function validateGraph(raw){
 if(!raw||!Array.isArray(raw.nodes)||!Array.isArray(raw.edges)||raw.nodes.length>90||raw.edges.length>200)throw Error('Μη έγκυρο γράφημα ή υπέρβαση ορίου.');
 const g={nodes:[],edges:[],assisted:!!raw.assisted};const ids=new Set();
 for(const r of raw.nodes){if(!r||!Object.hasOwn(NODES,r.type)||typeof r.id!=='string'||!(/^[A-Za-z0-9_-]{1,60}$/).test(r.id)||ids.has(r.id))throw Error('Μη έγκυρος ή διπλός κόμβος.');ids.add(r.id);const n=node(r.type,Math.max(-3000,Math.min(8000,Number(r.x)||0)),Math.max(-3000,Math.min(8000,Number(r.y)||0)),r.id);
 for(const pin of NODES[r.type].ins){if(pin.type==='exec')continue;const v=r.values?.[pin.id];if(v===undefined)continue;if(pin.type==='float'&&typeof v==='number'&&Number.isFinite(v))n.values[pin.id]=Math.max(-1e5,Math.min(1e5,v));else if(pin.type==='bool'&&typeof v==='boolean')n.values[pin.id]=v;else if(pin.type==='string'&&typeof v==='string')n.values[pin.id]=v.slice(0,1000);else if(['vector','rotator'].includes(pin.type)&&Array.isArray(v)&&v.length===3&&v.every(Number.isFinite))n.values[pin.id]=v.map(x=>Math.max(-1e5,Math.min(1e5,x)));else if(['actor','pawn','scene'].includes(pin.type)&&[null,'self','torchA','torchB','door'].includes(v))n.values[pin.id]=v;}
 g.nodes.push(n);}
 const eids=new Set();for(const r of raw.edges){if(!r||typeof r.id!=='string'||!(/^[A-Za-z0-9_-]{1,60}$/).test(r.id)||eids.has(r.id))throw Error('Μη έγκυρο καλώδιο.');eids.add(r.id);const e={id:r.id.slice(0,60),from:r.from,out:r.out,to:r.to,in:r.in};const err=validateConnection(g,e);if(err)throw Error(err);g.edges.push(e);}return g;
}
function newWorld(){return {x:-220,y:0,z:0,distance:0,hasKey:false,lights:{torchA:false,torchB:true},doorAngle:0,doorVisible:true,inputIgnored:false,walk:0,log:[],actions:[],trace:[],visited:[],values:{},lockedTest:false,unlockedTest:false,collisions:0};}
class Runtime{
 constructor(g,hook=()=>{}){this.graph=g;this.hook=hook;this.world=newWorld();this.running=false;this.paused=false;this.queue=[];this.pending=[0,0,0];this.currentInput=0;}
 reset(){this.running=false;this.paused=false;this.queue=[];this.pending=[0,0,0];this.world=newWorld();this.hook('reset');}
 log(text,kind='info'){this.world.log.unshift({text,kind,time:Date.now()});this.world.log=this.world.log.slice(0,70);this.hook('log');}
 start(step=false){const key=this.world.hasKey;this.reset();this.world.hasKey=key;this.running=true;this.paused=step;this.event('begin',0,!step);this.log(step?'Βηματική δοκιμή: πάτα «Επόμενος κόμβος».':'Play: το BeginPlay εκτελείται τώρα.');}
 stop(){this.running=false;this.paused=false;this.queue=[];this.pending=[0,0,0];this.currentInput=0;this.hook('stop');}
 mark(n){this.world.visited.push(n.id);this.world.visited=this.world.visited.slice(-20);this.hook('node',n.id);}
 input(n,pin,depth=0){const e=this.graph.edges.find(e=>e.to===n.id&&e.in===pin);if(e){this.hook('edge',e.id);const v=this.output(e.from,e.out,depth+1);this.world.values[n.id+'.'+pin]=v;return v;}return n.values[pin];}
 output(id,pin,depth=0){if(depth>60)throw Error('Υπέρβαση βάθους δεδομένων.');const n=this.graph.nodes.find(n=>n.id===id);if(!n)throw Error('Λείπει πηγή δεδομένων.');let v;switch(n.type){case 'input':v=this.currentInput;break;case 'forward':if(this.input(n,'target',depth)!=='self')throw Error('Το Target δεν είναι Actor.');v=[1,0,0];break;case 'vector':v=['x','y','z'].map(k=>this.input(n,k,depth));break;case 'key':v=this.world.hasKey;break;case 'torch':v='torchA';break;case 'torchB':v='torchB';break;case 'door':v='door';break;case 'rotator':v=['pitch','yaw','roll'].map(k=>this.input(n,k,depth));break;default:throw Error('Αυτή η έξοδος δεν δίνει δεδομένα.');}this.world.values[id+'.'+pin]=v;this.hook('data',id);return v;}
 next(id,out){for(const e of this.graph.edges.filter(e=>e.from===id&&e.out===out)){this.world.trace.push(e.id);this.world.trace=this.world.trace.slice(-25);this.hook('edge',e.id);this.queue.push(e.to);}}
 event(type,value=0,drain=true){if(!this.running)return;this.currentInput=value;this.pending=[0,0,0];for(const n of this.graph.nodes.filter(n=>n.type===type)){this.queue.push(n.id);}if(drain)this.drain();}
 step(){if(!this.running)return;if(!this.queue.length){this.log('Η διαδρομή τελείωσε. Κάνε νέα δοκιμή ή ενεργοποίησε την αλληλεπίδραση.');return;}this.execute(this.queue.shift());this.integrate(1/60);}
 drain(){let c=0;while(this.queue.length&&c++<300&&this.running){this.execute(this.queue.shift());}if(c>=300){this.log('Σταμάτησα για ασφάλεια: υπερβολικά πολλές εντολές.','error');this.stop();}}
 execute(id){const n=this.graph.nodes.find(n=>n.id===id);if(!n)return;try{this.mark(n);let out='out';switch(n.type){case 'begin':break;case 'input':out='triggered';break;case 'interact':out='started';break;case 'print':{const text=String(this.input(n,'text'));this.log(text,'print');this.world.actions.push({type:'print',text});break;}
 case 'branch':{const b=!!this.input(n,'condition');out=b?'true':'false';this.world.actions.push({type:'branch',value:b});if(!b)this.world.lockedTest=true;break;}
 case 'move':{if(this.input(n,'target')!=='self')throw Error('Add Movement Input: το Target πρέπει να είναι ο Pawn/Character σου.');const d=this.input(n,'direction'),s=Number(this.input(n,'scale'));if(!Array.isArray(d)||d.length!==3||!d.every(Number.isFinite)||!Number.isFinite(s))throw Error('Χρειάζεται έγκυρη κατεύθυνση Vector και αριθμός Scale.');if(!this.world.inputIgnored||this.input(n,'force'))this.pending=this.pending.map((v,i)=>v+d[i]*s);this.world.actions.push({type:'move',direction:d,scale:s});break;}
 case 'visible':{const t=this.input(n,'target'),v=!!this.input(n,'visible');if(t==='torchA'||t==='torchB')this.world.lights[t]=v;else if(t==='door')this.world.doorVisible=v;else throw Error('Set Visibility: λείπει έγκυρο Scene Component στο Target. Πρόσθεσε TorchLight_A και σύνδεσε τη μπλε έξοδο.');this.world.actions.push({type:'visible',target:t,value:v});break;}
 case 'rotate':{const t=this.input(n,'target'),r=this.input(n,'rotation');if(t!=='door')throw Error('Εδώ περιστρέφουμε μόνο το DoorPivot. Σύνδεσε τη δική του αναφορά στο Target.');if(r[0]!==0||r[2]!==0)throw Error('Το εργαστήριο πόρτας υποστηρίζει μόνο Yaw. Θέσε Pitch και Roll σε 0.');this.world.doorAngle=r[1];if(this.world.hasKey&&Math.abs(r[1])>=70)this.world.unlockedTest=true;this.world.actions.push({type:'rotate',value:r[1]});break;}
 default:throw Error('Αυτός ο καθαρός κόμβος δίνει δεδομένα, δεν εκτελείται από λευκό καλώδιο.');}
 this.world.actions=this.world.actions.slice(-160);this.next(id,out);this.hook('state');}catch(e){this.log(e.message,'error');this.queue=[];this.stop();}}
 frame(dt,value){if(!this.running||this.paused)return;if(value!==0)this.event('input',value);this.integrate(dt);}
 integrate(dt){if(!this.running)return;const m=Math.hypot(...this.pending);const d=m>1?this.pending.map(x=>x/m):this.pending;let dx=d[0]*160*Math.min(dt,.05),dy=d[1]*160*Math.min(dt,.05);const old=[this.world.x,this.world.y];const xmax=Math.abs(this.world.doorAngle)>65?450:330;this.world.x=Math.max(-330,Math.min(xmax,this.world.x+dx));this.world.y=Math.max(-240,Math.min(240,this.world.y+dy));this.world.distance+=Math.hypot(this.world.x-old[0],this.world.y-old[1]);this.world.walk+=Math.hypot(dx,dy)*.06;this.pending=[0,0,0];if(dx||dy)this.hook('state');}
}
function starter(id){const g={nodes:[],edges:[],assisted:false};if(id==='first')g.nodes=[node('begin',70,90,'a'),node('print',410,90,'b')];if(['walk','repair'].includes(id)){g.nodes=[node('input',40,60,'a'),node('forward',40,290,'b'),node('move',430,100,'c')];if(id==='repair')g.edges=[edge('a','triggered','c','in'),edge('a','value','c','scale')];}if(id==='light')g.nodes=[node('begin',40,70,'a'),node('torch',40,240,'b'),node('visible',410,80,'c')];if(id==='door')g.nodes=[node('interact',40,50,'a'),node('key',40,220,'b'),node('branch',330,60,'c'),node('door',340,300,'d'),node('rotate',650,50,'e'),node('print',650,330,'f')];if(id==='door')g.nodes.find(n=>n.id==='f').values.text='Η πόρτα είναι κλειδωμένη. Χρειάζεσαι το κλειδί.';return g;}
function solution(id){const g=starter(id);g.assisted=true;if(id==='first')g.edges=[edge('a','out','b','in')];if(['walk','repair'].includes(id))g.edges=[edge('a','triggered','c','in'),edge('b','value','c','direction'),edge('a','value','c','scale')];if(id==='light')g.edges=[edge('a','out','c','in'),edge('b','value','c','target')];if(id==='door')g.edges=[edge('a','started','c','in'),edge('b','value','c','condition'),edge('c','true','e','in'),edge('d','value','e','target'),edge('c','false','f','in')];return g;}
function diagnose(g,r,lesson){const errors=r.world.log.filter(l=>l.kind==='error');if(errors.length)return errors[0].text;const type=lesson==='light'?'visible':lesson==='door'?'branch':lesson==='first'?'print':'move';const n=g.nodes.find(n=>n.type===type);if(!n)return `Λείπει ο κόμβος ${NODES[type].title}. Άνοιξε «+ Κόμβος» και πρόσθεσέ τον.`;if(!g.edges.some(e=>e.to===n.id&&e.in==='in'))return `Ο ${NODES[type].title} δεν έχει λευκή σύνδεση εκτέλεσης. Η παρουσία του στον καμβά δεν αρκεί.`;if(type==='move'&&!g.edges.some(e=>e.to===n.id&&e.in==='direction')&&Math.hypot(...n.values.direction)===0)return 'Η κατεύθυνση είναι (0,0,0). Σύνδεσε το Return Value του Get Actor Forward Vector στο World Direction.';if(type==='move'&&!g.edges.some(e=>e.to===n.id&&e.in==='scale'))return 'Το Scale Value χρησιμοποιεί τη σταθερή τιμή του. Για σωστό W/S σύνδεσε το Action Value, ώστε το S να δίνει −1.';if(type==='visible'&&!g.edges.some(e=>e.to===n.id&&e.in==='target'))return 'Ποιο φως πρέπει να αλλάξει; Σύνδεσε TorchLight_A → Target.';if(!r.running)return 'Οι συνδέσεις είναι έτοιμες για έλεγχο. Πάτησε «Δοκιμή»· το γράφημα δεν εκτελείται όσο το σχεδιάζεις.';if(type==='move')return 'Η σύνδεση φαίνεται έτοιμη. Κράτησε W ή το κουμπί «Μπροστά» στη σκηνή. Στόχος: 200 cm πραγματικής μετατόπισης.';if(type==='branch')return 'Δοκίμασε E χωρίς κλειδί. Μετά ενεργοποίησε «Έχω κλειδί» και πάτησε E ξανά. Παρατήρησε τις δύο διαφορετικές εξόδους.';return 'Παρατήρησε το ίχνος εκτέλεσης και το συγκεκριμένο αντικείμενο στη σκηνή. Άλλαξε μία μόνο τιμή και κάνε νέα δοκιμή.';}
const API={NODES,SOURCES,node,edge,clone,Runtime,starter,solution,validateConnection,validateGraph,diagnose,newWorld};if(typeof module!=='undefined')module.exports=API;root.DM=API;
})(typeof window!=='undefined'?window:globalThis);
